drop table if exists EBB049L CASCADE;

create table EBB049l
(
    trnSrn bigint generated by default as identity,
    trnYmd varchar(8),
    sender varchar(20),
    receiver varchar(20),
    amt  bigint,
    status varchar(1),
    primary key (trnSrn, sender)
);